### ISSUE TITLE
CSV import teaser provides incomplete and wrong information

### ISSUE THREAD

**Issue by sunweaver** [gosa-project/gosa-plugins-ldapmanager#2]
When using the CSV Import it says
"you must have at least the UID, GIVENNAME and SURNAME set.".

Giving that a try, it stops/fails after adding the first user.

[1] correctly states "At least, entries for the following fields have to
be provided: uid, last name (sn), first name (givenName) and password"

So, not only is the list incomplete, the capitalisation is wrong or at
least misleading.

The localizations are wrong as well, though e.g. the french one at least
does the capitalisation right.

Reported by Philipp Hübner as Debian bug #782535.

**Comment by schweer-guest** [comment]
I figure 'update-locale' (gosa-gore) has to be run to finally fix DebBug #782535; also, translators should be informed to update the XX.po files (see https://github.com/gosa-project/gosa-plugins-ldapmanager/tree/master/locale).
